### ISSUE TITLE
No event end time in calendar view

### ISSUE THREAD

**Issue by bkr1969** [totaldebug/atomic-calendar-revive#927] opened 2023-01-25 14:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The event list in calendar view shows only the start time, i.e. 1500: -    with no end time.

### Expected behaviour

The end time shows in the event view, just not calendar view

### Card Version

Current

### Home Assistant Version

2022.12.1

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Calendar Card
entities:
  - entity: calendar.family_3
    name: Family
    icon: mdi:human-male-female-child
    color: black
    maxDaysToShow: 50
  - entity: calendar.anylist_meal_plan
    name: Anylist meal plan
    icon: mdi:silverware-fork-knife
    color: grey
  - entity: calendar.garbage_collection
    name: Garbage Collection
    icon: mdi:delete
    color: blue
  - entity: calendar.ohio_state_buckeyes
    name: Ohio state buckeyes
    icon: mdi:football
    color: red
  - entity: calendar.apple
    name: Apple
    icon: mdi:human-male-female-child
    color: black
style: |
  ha-card {
    background: rgba(255,255,255,1.0);
    height: 100px;
    box-shadow: 5;
    --primary-text-color: black;
    --secondary-text-color: var(--primary-text-color);
  }
enableModeChange: true
defaultMode: Calendar
calShowDescription: true
showLastCalendarWeek: false
disableCalEventLink: false
disableCalLink: true
firstDayOfWeek: 0
maxDaysToShow: 10
refreshInterval: 60
showDate: true
showRelativeTime: true
showMultiDay: false
hideDuplicates: true
sortByStartTime: true
showCurrentEventLine: true
calEventTime: true
showMonth: true
showFullDayProgress: true
showWeekDay: false
showEventIcon: true
showCalendarName: true
showHiddenText: false
showDatePerEvent: false
disableCalLocationLink: false
showMultiDayEventParts: true
hideFinishedEvents: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment] 2023-02-22 19:06
This is by design. I can change this to a feature request if you need this?

**Comment by marksie1988** [comment] 2023-03-09 12:46
Closing as there has been no update

**Closed by marksie1988** 2023-03-09 12:46 UTC
Labels: type/bug
