### ISSUE TITLE
Using maxEventCount hides some events that should be shown

### ISSUE THREAD

**Issue by johnekarlsson** [totaldebug/atomic-calendar-revive#1378] opened 2024-01-18 18:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="116" alt="Screenshot 2024-01-18 at 10 38 39" src="https://github.com/totaldebug/atomic-calendar-revive/assets/63417088/6f2d3ea8-68d9-4e1c-8f98-fa0ed87291d4">

### Expected behaviour

<img width="109" alt="Screenshot 2024-01-18 at 10 37 23" src="https://github.com/totaldebug/atomic-calendar-revive/assets/63417088/3c1746f6-04ac-40be-9cf8-139e607bbf73">

### Steps To Reproduce

Using the attached config, _with_ the last line should show the six first events, from the list that is shown _without_ the last line. 

As can be seen in the Current Behavior-picture, the events the 22nd and 23rd are left out, even if they are among the first six events.

### Mode

Calendar

### Card Version

9.3.0 Beta 3

### Home Assistant Version

2024.1.2

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
   - entity: calendar.xxxx
maxEventCount: 6
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment] 2024-01-18 21:19
Think this will be related to #1338 currently looking at this issue I'll double check with this too

**Comment by Pscharumbel** [comment] 2024-01-20 20:08
Unfortunately, the error still persists for me despite version 9.4.0. 😢

**Comment by marksie1988** [comment] 2024-01-20 20:12
Yes this issue hasn't been resolved. 

The release notes will let you know what's been fixed on each version and should be checked before installing. 

Once an issue is resolved and released it will automatically close by the release workflow. Generally I don't close an issue without having confirmation from a beta test that it's working. 

This will likely be the next issue that I look into.

**Comment by Pscharumbel** [comment] 2024-01-20 20:21
Oh, sorry. I thought it was the same as #1338. My bad English. 😬

**Comment by marksie1988** [comment] 2024-01-20 20:23
Ah no, it's related to the same thing, but a different scenario.  I need to do some tests and will release a fix soon. 

Hopefully in next few days if it's not too complex.

**Comment by Pscharumbel** [comment] 2024-01-20 20:52
Thank you!

**Comment by johnekarlsson** [comment] 2024-01-23 10:02
It works! All issues resolved. Thanks' alot!

Den tis 23 jan. 2024 kl 10:35 skrev Steven Marks ***@***.***>:

**Comment by Pscharumbel** [comment] 2024-01-23 10:15
Really? Not for me. What am I doing wrong? 😫

**Comment by marksie1988** [comment] 2024-01-23 10:28
@Pscharumbel please send the following for me to troubleshoot:

1: a copy of your card config
2: press f12 click the console tab and send a screenshot of the "atomic calendar revive" entry
3: screenshot of what you see 
4: screenshot of what you expect to see

Hopefully this will give me enough to figure out what's wrong

**Comment by Pscharumbel** [comment] 2024-01-23 10:40
Alright!

1:
type: custom:atomic-calendar-revive
name: null
enableModeChange: true
entities:
  - entity: calendar.geburtstage
    name: Geburtstage
  - entity: calendar.tine_jens
  - entity: calendar.abfallkalender
    name: Abfallkalender
  - entity: calendar.feiertage_brandenburg
showDate: false
showLoader: false
showRelativeTime: false
showLocation: false
showMultiDay: true
maxEventCount: 5
maxDaysToShow: 4
hideDuplicates: false
showMultiDayEventParts: true
compactMode: false
offsetHeaderDate: false
showAllDayEvents: true
hoursOnSameLine: false
showAllDayHours: false
showTimeRemaining: false
showEventDate: true
showWeekNumber: false
showDatePerEvent: false
showProgressBar: false
showWeekDay: true
showDescription: false
disableEventLink: false
disableLocationLink: false
showNoEventsForToday: false
showFullDayProgress: false
showMonth: false
showCalendarName: false
showHiddenText: false
disableCalLink: false
allDayBottom: false
card_mod:
  style: |
    ha-card {
      margin-top: -9px;
      font-size: 15px;
      color: #808080;
      line-height: 170%;  
    }

2:
![Unbenannt](https://github.com/totaldebug/atomic-calendar-revive/assets/121807392/8b7148db-080f-43e7-9a61-a2d8045efade)

3:
Without: maxDaysToShow: 4
![1](https://github.com/totaldebug/atomic-calendar-revive/assets/121807392/09e2a692-d294-4852-bd26-e28040317b3b)

4:
With: maxDaysToShow: 4
![2](https://github.com/totaldebug/atomic-calendar-revive/assets/121807392/cf8c159f-a9cf-438d-987d-8714e16a7caa)

**Comment by Pscharumbel** [comment] 2024-01-23 10:41
I hope it helps!

**Comment by marksie1988** [comment] 2024-01-24 12:09
@Pscharumbel I have just done a new release, please try with v9.4.0-beta.5

**Comment by Pscharumbel** [comment] 2024-01-24 12:21
Hello! 
Thank you very much for your effort! At first, it seemed to work perfectly. I only had one appointment per day. When I added a second one for Thursday, unfortunately, the appointment on Friday disappeared, and the one on Saturday was displayed.
Best regards!

**Comment by marksie1988** [comment] 2024-01-26 08:47
are the events you added in different or the same calendar?

I'm struggling to replicate your issue.

**Comment by Pscharumbel** [comment] 2024-01-27 08:24
Hi! 
I use multiple calendars with a mix of all-day and timed events. As a test, I've added and deleted some appointments, and tried different values for maxEventCount, and I couldn't reproduce the error anymore. 🤷🏻‍♂️
So, tank you very much again for your work!! 😃👌🏼

**Closed** 2024-01-28 09:50 UTC
Labels: type/bug, released on @beta
