### ISSUE TITLE
Dutch (nl) support

### ISSUE THREAD

**Issue by kduthoy** [totaldebug/atomic-calendar-revive#1442] opened 2024-03-10 16:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello
Can you add dutch (nl) support? I would like to see the text "All day" translated to "Volledige dag".
Thanks!

### Expected behaviour

Show the text in dutch.

### Mode

Event (default)

### Card Version

Latest

### Home Assistant Version

2024.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment] 2024-03-20 11:39
this is not a bug, closing, feature requests need to go in discussions

**Closed by marksie1988** 2024-03-20 11:39 UTC
Labels: type/bug
